name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Change this to the branch your client will use to make updates
      -
permissions:
  contents: write  # Allow write access to repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use the version that your app requires

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages  # The branch you want to deploy to
          cname: portobellodrivertraining.com  # Add your custom domain here
